package com.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DemoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemoAllPropertiesEquals(Demo expected, Demo actual) {
        assertDemoAutoGeneratedPropertiesEquals(expected, actual);
        assertDemoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemoAllUpdatablePropertiesEquals(Demo expected, Demo actual) {
        assertDemoUpdatableFieldsEquals(expected, actual);
        assertDemoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemoAutoGeneratedPropertiesEquals(Demo expected, Demo actual) {
        assertThat(expected)
            .as("Verify Demo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemoUpdatableFieldsEquals(Demo expected, Demo actual) {
        assertThat(expected)
            .as("Verify Demo relevant properties")
            .satisfies(e -> assertThat(e.getUsername()).as("check username").isEqualTo(actual.getUsername()))
            .satisfies(e -> assertThat(e.getMobileNumber()).as("check mobileNumber").isEqualTo(actual.getMobileNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemoUpdatableRelationshipsEquals(Demo expected, Demo actual) {
        // empty method
    }
}
