name: habittracker
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  habittracker_openapi:
    path: ./openapi
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0 
  google_fonts: 6.1.0
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: 1.19.0
  equatable: ^2.0.7
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  flutter_tts: 4.2.0
  go_router: 12.1.3
  intl: 0.19.0
  livespeechtotext: 1.0.9
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  provider: 6.1.2
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  timeago: 3.6.1
  translator: 1.0.3+1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2
  deepgram_speech_to_text: 2.3.2
  flutter_sound: 9.17.8
  http_multi_server: 3.2.2
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^4.2.1

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.5  # Use the latest compatible version
  json_serializable: ^6.0.1  # Only if you're using json_serializable
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

 

flutter:

  
  uses-material-design: true

