package com.lxisoft.emergencyalert.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BatteryStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatteryStatusAllPropertiesEquals(BatteryStatus expected, BatteryStatus actual) {
        assertBatteryStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertBatteryStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatteryStatusAllUpdatablePropertiesEquals(BatteryStatus expected, BatteryStatus actual) {
        assertBatteryStatusUpdatableFieldsEquals(expected, actual);
        assertBatteryStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatteryStatusAutoGeneratedPropertiesEquals(BatteryStatus expected, BatteryStatus actual) {
        assertThat(expected)
            .as("Verify BatteryStatus auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatteryStatusUpdatableFieldsEquals(BatteryStatus expected, BatteryStatus actual) {
        assertThat(expected)
            .as("Verify BatteryStatus relevant properties")
            .satisfies(e -> assertThat(e.getBatteryLevel()).as("check batteryLevel").isEqualTo(actual.getBatteryLevel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatteryStatusUpdatableRelationshipsEquals(BatteryStatus expected, BatteryStatus actual) {
        // empty method
    }
}
