package com.lxisoft.emergencyalert.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GeoFenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoFenceAllPropertiesEquals(GeoFence expected, GeoFence actual) {
        assertGeoFenceAutoGeneratedPropertiesEquals(expected, actual);
        assertGeoFenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoFenceAllUpdatablePropertiesEquals(GeoFence expected, GeoFence actual) {
        assertGeoFenceUpdatableFieldsEquals(expected, actual);
        assertGeoFenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoFenceAutoGeneratedPropertiesEquals(GeoFence expected, GeoFence actual) {
        assertThat(expected)
            .as("Verify GeoFence auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoFenceUpdatableFieldsEquals(GeoFence expected, GeoFence actual) {
        assertThat(expected)
            .as("Verify GeoFence relevant properties")
            .satisfies(e -> assertThat(e.getSafeZones()).as("check safeZones").isEqualTo(actual.getSafeZones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoFenceUpdatableRelationshipsEquals(GeoFence expected, GeoFence actual) {
        // empty method
    }
}
